[package]
name = "wasm-yew-minimal"
version = "0.1.0"
authors = ["Michael Freeborn <michaelfreeborn1@gmail.com>"]
edition = "2021"

[dependencies]
plotly = { version="0.8.4", features = ["wasm"] }
yew = { version="0.21.0", features = ["csr"] }
yew-hooks = "0.3.2"
log = "0.4"
wasm-logger = "0.2"

